### ISSUE TITLE
Custom CSS properties

### ISSUE THREAD

**Issue by certainlyakey** [lagden/postcss-inline-base64#6]
Hi! 
Thanks for a great plugin. Has been an awesome experience to work with it.
I'm struggling to make it work with a CSS variable though. 
What i want is to put the generated base64 code into a CSS variable to avoid it to appear multiple times in CSS.
Something like this: 

```
:root {
  --image-mainmenu-bg: url(b64---'img/mainmenu-bg.png'---);
}
```

This however doesn't work, no PostCSS transformation happens and the resulting CSS contains literal string `url(b64---'img/mainmenu-bg.png'---);`. I tried different syntaxes.

Is there any way this could be resolved?

**Comment by lagden** [comment]
humm... it's not implemented!!

I will take look!

**Comment by lagden** [comment]
now is working, but you'll have to use PostCSS 8

**Comment by certainlyakey** [comment]
Thanks a lot, will try it!
